name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the form below to help us understand and reproduce the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have read the [documentation](https://github.com/pegasusheavy/ngx-bun#readme)
          required: true
        - label: I am using a supported version of Angular (19+) and Bun (1.0+)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a new Angular project with `ng new my-app`
        2. Run `ng add @pegasusheavy/ngx-bun`
        3. Start the server with `npm run dev:ssr`
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe the actual behavior...
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If applicable, paste any error messages or stack traces
      render: shell
      placeholder: |
        Error: Something went wrong
            at Function.something (/path/to/file.js:123:45)
            ...

  - type: input
    id: ngx-bun-version
    attributes:
      label: "@pegasusheavy/ngx-bun Version"
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: angular-version
    attributes:
      label: Angular Version
      placeholder: "19.0.0"
    validations:
      required: true

  - type: input
    id: bun-version
    attributes:
      label: Bun Version
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Windows (WSL)
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem
      placeholder: Any additional information...

  - type: textarea
    id: reproduction-repo
    attributes:
      label: Reproduction Repository
      description: If possible, provide a link to a minimal reproduction repository
      placeholder: https://github.com/username/repo
